// autogenerated: do NOT edit manually
using Platinum.Configuration;
using System;
using System.ComponentModel;
using System.Configuration;
using KvConfig = Platinum.Configuration.KeyValueConfigurationElement;
using NullableString = Platinum.Configuration.NullableString;

namespace Gold.Forms
{
    /// <summary />
    public partial class FormsConfiguration : ConfigurationSection
    {
        /// <summary>
        /// Gets the configuration instance for section 'gold/xforms'
        /// </summary>
        public static FormsConfiguration Current
        {
            get { return AppConfiguration.SectionGet<FormsConfiguration>( "gold/xforms" ); }
        }


        /// <summary />
        [ConfigurationProperty( "namespaces", IsDefaultCollection = false )]
        [ConfigurationCollection( typeof( FormsNamespaceConfiguration ), AddItemName = "add" )]
        public ConfigurationElementCollection<FormsNamespaceConfiguration> Namespaces
        {
            get { return (ConfigurationElementCollection<FormsNamespaceConfiguration>) base[ "namespaces" ]; }
        }


        /// <summary />
        [ConfigurationProperty( "properties", IsDefaultCollection = false )]
        [ConfigurationCollection( typeof( FormsPropertyConfiguration ), AddItemName = "add" )]
        public ConfigurationElementCollection<FormsPropertyConfiguration> FormProperties
        {
            get { return (ConfigurationElementCollection<FormsPropertyConfiguration>) base[ "properties" ]; }
        }
    }


    /// <summary />
    public partial class FormsNamespaceConfiguration : ConfigurationElement
    {

        /// <summary />
        [ConfigurationProperty( "prefix", IsKey = true, IsRequired = true )]
        public string Prefix
        {
            get { return (string) this[ "prefix" ]; }
            set { this[ "prefix" ] = value; }
        }


        /// <summary />
        [ConfigurationProperty( "namespace", IsKey = true, IsRequired = true )]
        public string Namespace
        {
            get { return (string) this[ "namespace" ]; }
            set { this[ "namespace" ] = value; }
        }
    }


    /// <summary />
    public partial class FormsPropertyConfiguration : ConfigurationElement
    {

        /// <summary />
        [ConfigurationProperty( "name", IsKey = true, IsRequired = true )]
        public string Name
        {
            get { return (string) this[ "name" ]; }
            set { this[ "name" ] = value; }
        }


        /// <summary />
        [ConfigurationProperty( "type", IsRequired = true )]
        public string Moniker
        {
            get { return (string) this[ "type" ]; }
            set { this[ "type" ] = value; }
        }
    }

}

/* eof */
